version: "3.8"
services:
  scarpper:
    image: python-cli
    restart: on-failure
    depends_on:
      broker:
        condition: service_healthy
    command: "celery -A tasks worker -B"
    volumes:
      - "./scrapper:/home/app/cli"

  scarp_result_consumer:
    image: python-web
    depends_on:
      broker:
        condition: service_healthy
    command: "python consumer.py"
    volumes:
      - "./webApp:/home/app/site"
  web_app:
    image: python-web
    command: "bash -c 'python manage.py runserver'"
    volumes:
      - "./webApp:/home/app/site"

#  database:
#    image: mysql
  broker:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
