# Generated by Django 4.2.1 on 2023-05-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation', models.CharField(max_length=100)),
                ('governorate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('isShop', models.BooleanField()),
                ('avatar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('imgLoad', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('phone', models.CharField(max_length=100)),
                ('publishedOn', models.DateTimeField()),
                ('isModified', models.BooleanField()),
                ('subCategory', models.CharField(max_length=30)),
                ('isFeatured', models.BooleanField()),
                ('producttype', models.IntegerField()),
                ('images', models.ManyToManyField(to='tayara_stats.media')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tayara_stats.location')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tayara_stats.publisher')),
            ],
        ),
    ]
