# Generated by Django 4.2.1 on 2023-05-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('imgLoad', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('phone', models.CharField(max_length=100)),
                ('publishedOn', models.DateTimeField()),
                ('isModified', models.BooleanField()),
                ('subCategory', models.CharField(max_length=30)),
                ('isFeatured', models.BooleanField()),
                ('producttype', models.IntegerField()),
                ('images', models.JSONField()),
                ('pub_isApproved', models.BooleanField()),
                ('pub_name', models.CharField(max_length=100)),
                ('pub_isShop', models.BooleanField()),
                ('pub_avatar', models.CharField(max_length=100)),
                ('loc_delegation', models.CharField(max_length=100)),
                ('loc_governorate', models.CharField(max_length=100)),
            ],
        ),
    ]
